# Generated by Django 4.2.3 on 2023-07-28 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_rename_timestamp_message_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='command',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
